# Generated by Django 5.1.3 on 2025-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_number', models.CharField(max_length=20, unique=True)),
                ('c_name', models.CharField(max_length=200)),
                ('c_des', models.TextField()),
                ('c_teacher', models.CharField(max_length=100)),
                ('c_credit', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_email', models.CharField(max_length=100)),
                ('c_number', models.CharField(max_length=20)),
                ('status', models.CharField(default='p', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_fname', models.CharField(max_length=30)),
                ('s_lname', models.CharField(max_length=30)),
                ('s_email', models.EmailField(max_length=150)),
                ('s_phone', models.IntegerField(default=0)),
                ('s_dob', models.DateField()),
                ('s_city', models.CharField(max_length=50)),
                ('s_password', models.CharField(max_length=20)),
                ('s_image', models.ImageField(upload_to='media/profilepic')),
                ('s_document', models.FileField(upload_to='media/documents')),
                ('s_bio', models.TextField()),
            ],
        ),
    ]
