# Generated by Django 5.2.1 on 2025-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
