# Generated by Django 5.2.1 on 2026-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_student_s_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
